---
- name: Transfer and execute a script.
  hosts: all
  tasks:
     - name: Copy files
       copy: src={{ item.src }} dest={{ item.dest }}
       with_items:
         - { src: '/root/.ssh/ida_rsa.pub', dest: '/root/.ssh/' }
         - { src: '/root/.ssh/id_rsa', dest: '/root/.ssh/' }
